elasticsearch:
  host: driver-book-elk
  port: 9200
  index:
    name:
      drivers: "db-drivers"
      statistics: "db-statistics"
      enriched-drivers: "db-enriched-drivers"
  pipeline:
    name: "driver-enrichment-pipeline"
    path: "pipeline/driver-enrichment.json"
  policy:
    name: "enrich-statistics-policy"
